# Generated by Django 4.2.4 on 2025-01-19 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_group_user_groups_group_permissions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='entrerprise',
            new_name='enterprise',
        ),
    ]
